spring:
  datasource:
    name: miaosha
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
   #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8090
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  global-config:
    db-config:
      id-type: auto